[tool.poetry]
name = "django-app"
version = "0.1.0"
description = ""
authors = ["stefan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
